blueprint:
  name: Keypad 5 button cypher to turn something on
#  source_url: https://community.home-assistant.io/t/door-open-tts-cloud-say-announcer-nabu-casa-required/316046
  domain: automation
  input:
    button_one:
      name: Button Press One
      description: Binary Sensor for First Button Pressed
      selector:
        entity:
          domain: binary_sensor
    button_two:
      name: Button Press Two
      description: Binary Sensor for Second Button Pressed
      selector:
        entity:
          domain: binary_sensor
    button_three:
      name: Button Press Three
      description: Binary Sensor for Third Button Pressed
      selector:
        entity:
          domain: binary_sensor
    button_four:
      name: Button Press Four
      description: Binary Sensor for Forth Button Pressed
      selector:
        entity:
          domain: binary_sensor
    button_five:
      name: Button Press Five
      description: Binary Sensor for Fifth Button Pressed
      selector:
        entity:
          domain: binary_sensor
    lock_control:
      name: Buffer for the Final Lock Enable
      description: input_boolean - Final Lock Enable to trigger your lock or action
      selector:
        entity:
          domain: input_boolean
    seq_status:
      name: Control Sequence Status Number
      description: input_number - The lock sequence number (set range to 0 to 32)
      selector:
        entity:
          domain: input_number
    on_timer:
      name: Lock on Time in Seconds
      description: Time output signal is on in seconds
      default: 60
      selector:
        number:
          min: 5
          max: 360
          unit_of_measurement: "seconds"
          mode: slider

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_one
    id: pad1
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input button_two
    id: pad2
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input button_three
    id: pad3
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input button_four
    id: pad4
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input button_five
    id: pad5
    from: "off"
    to: "on"

action:
  - choose:
    - alias: somebody pushed the first button
      conditions:
        - condition: trigger
          id: 'pad1'
      sequence:
        - alias: Set seq number to 1
          service: input_number.set_value
          data:
            entity_id: !input seq_status
            value: 1
    - alias: Button 2 pushed in correct order
      conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: 'pad2'
            - condition: template 
              value_template: "{{ is_state('!input seq_status', '1.0') }}"
      sequence:
        - alias: Set seq number to 3
          service: input_number.set_value
          data:
            value: 3
          target:
            entity_id: !input seq_status
    - alias: Button 3 pushed in correct order
      conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: 'pad3'
            - condition: template 
              value_template: "{{ is_state('!input seq_status', '3.0') }}"
      sequence:
        - alias: Set seq number to 7
          service: input_number.set_value
          data:
            value: 7
          target:
            entity_id: !input seq_status
    - alias: Button 4 pushed in correct order
      conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: 'pad4'
            - condition: template 
              value_template: "{{ is_state('!input seq_status', '7.0') }}"
      sequence:
        - alias: Set seq number to 15
          service: input_number.set_value
          data:
            value: 15
          target:
            entity_id: !input seq_status
    - alias: Button 5 pushed in correct order
      conditions:
        - condition: and
          conditions:
            - condition: trigger
              id: 'pad5'
            - condition: template 
              value_template: "{{ is_state('!input seq_status', '15.0') }}"
      sequence:
        - alias: Set seq number to 31
          service: input_number.set_value
          data:
            value: 31
          target:
            entity_id: !input seq_status
        - alias: Enable the Lock
          service: input_boolean.turn_on
          entity_id: !input lock_control
        - alias: Leave the lock enabled for a time limit
          delay: !input on_timer
        - alias: Disable the Lock normal
          service: input_boolean.turn_off
          entity_id: !input lock_control
        - alias: Reset status number normal
          service: input_number.set_value
          data:
            value: 0
          target:
            entity_id: !input seq_status
#  Default is to abort here if none of the are conditions met on a button press.
    default:
      - alias: Reset status number on fail code
        service: input_number.set_value
        data:
          value: 0
        target:
          entity_id: !input seq_status
      - alias: Shut it down on fail code
        service: input_boolean.turn_off
        entity_id: !input lock_control
