blueprint:
  name: Watchdog for keypad
    # If key sequence fails make sure pad gets cleared
#  source_url: https://community.home-assistant.io/t/door-open-tts-cloud-say-announcer-nabu-casa-required/316046
  domain: automation
  input:
    code_one_buffer:
      name: Code One Buffer
      description: input_boolean - Buffer for First Button Pressed
      selector:
        entity:
          domain: input_boolean
    code_two_buffer:
      name: Code Two Buffer
      description: input_boolean - Buffer for Second Button Pressed
      selector:
        entity:
          domain: input_boolean
    code_three_buffer:
      name: Code Three Buffer
      description: input_boolean - Buffer for Third Button Pressed
      selector:
        entity:
          domain: input_boolean
    code_four_buffer:
      name: Code Four Buffer
      description: input_boolean - Buffer for Forth Button Pressed
      selector:
        entity:
          domain: input_boolean
    code_five_buffer:
      name: Code Five Buffer
      description: input_boolean - Buffer for Fifth Button Pressed
      selector:
        entity:
          domain: input_boolean
    lock_control:
      name: Buffer for the Final Lock Enable
      description: input_boolean - Final Lock Enable
      selector:
        entity:
          domain: input_boolean
    delay_timer:    
      description: Time allowed before abort - restart
      default: 5
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "minutes"
          mode: slider

mode: single

trigger:
  platform: state
  entity_id: !input button_one
  from: "off"
  to: "on"

variables:
  abort:
    - !input lock_control
    - !input code_one_buffer
    - !input code_two_buffer
    - !input code_three_buffer
    - !input code_four_buffer
    - !input code_five_buffer

action:
  - delay: !input delay_timer
  - alias: Shut them all down
    service: input_boolean.turn_off
    entity_id: "{{ abort }}"
