- id: '1671480644305'
  alias: Auto_Fan_test Office
  description: test new control
  use_blueprint:
    path: test/aaatestfan.yaml
    input:
      room_temp_now: sensor.lumi_lumi_sensor_cube_aqgl01_device_temperature
      mqtt_fan_topic: Office_Fan/cmnd/FanSpeed
      weekday:
      - mon
      - tue
      - wed
      - thu
      - sat
      - sun
      - fri
