- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.test_color
- id: 7b24d93c-d092-48f9-838d-233746babc21
  alias: aaaaAAAaaaaAAacc Person Alert Honitor
  description: Alert when we go places
  trace:
    stored_traces: 20
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      people2monitor:
      - person.julie
      - person.jen
      zone2monitor:
      - zone.home
      - zone.katy_s_kloset
      - zone.follicle_assembly_building
      - zone.feed_store
      - zone.nail_shop2
      - zone.belva
      - zone.clinic
      - zone.expo
      - zone.lakewood
      - zone.mountain
      - zone.shawano
      - zone.somerhome
      - zone.suring
      - zone.townsend
      enter_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: enter
        - service: script.personalert_audio
          data:
            mess: '{{ trigger.to_state.attributes.friendly_name + '' has arrived at
              '' + trigger.to_state.state }}'
            lang: en-GB
      leave_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.from_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.from_state.context.id }}'
            phase: leave
        - service: script.personalert_audio
          data:
            mess: '{{ trigger.from_state.attributes.friendly_name + '' has left ''
              + trigger.from_state.state }}'
            lang: en-GB
      jump_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: jump
        - service: script.personalert_audio
          data:
            mess: '{{ trigger.to_state.attributes.friendly_name + '' has left '' +
              trigger.from_state.state + '' and is located at: '' + trigger.to_state.state
              }}'
            lang: en-GB
      enable_time: 05:30:18
      disable_time: '20:27:36'
      hold_period:
        hours: 0
        minutes: 5
        seconds: 0
  mode: single
  max_exceeded: silent
- id: 8dc284dc-7cef-4ee5-8045-da04bbf495f2
  alias: aaaaAAAaaaaAAacc Jim Alert Honitor
  description: Alert when Jim Goes places
  trace:
    stored_traces: 20
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      people2monitor:
      - person.jim
      zone2monitor:
      - zone.home
      - zone.katy_s_kloset
      - zone.feed_store
      - zone.belva
      - zone.clinic
      - zone.expo
      - zone.lakewood
      - zone.mountain
      - zone.shawano
      - zone.suring
      - zone.somerhome
      - zone.townsend
      enter_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: enter
        - service: script.personalert_audio
          data:
            entities: media_player.home_group
            mess: '{{ trigger.to_state.attributes.friendly_name + '' has arrived at
              '' + trigger.to_state.state }}'
            lang: en-CA
            gend: male
      leave_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.from_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.from_state.context.id }}'
            phase: leave
        - service: script.personalert_audio
          data:
            entities: media_player.home_group
            mess: '{{ trigger.from_state.attributes.friendly_name + '' has left ''
              + trigger.from_state.state }}'
            lang: en-CA
            gend: male
      jump_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: jump
        - service: script.personalert_audio
          data:
            entities: media_player.home_group
            mess: '{{ trigger.to_state.attributes.friendly_name + '' has left '' +
              trigger.from_state.state + '' and is located at: '' + trigger.to_state.state
              }}'
            lang: en-CA
            gend: male
      enable_time: 05:29:13
      disable_time: 08:31:42
      hold_period:
        hours: 0
        minutes: 5
        seconds: 0
  mode: single
  max_exceeded: silent
- id: '1678783868302'
  alias: aaaaaaaaaaAaa BP Test
  description: Tarantula Nest
  use_blueprint:
    path: SirGoodenough/Octoprint_Discovery_Helper.yaml
    input:
      base_topic: octoPrint/tarantula/
      device_id: 7fcb2b57-4fac-42c2-93ba-1b2a4b54d366a
      device_name: TarantulaPro
      print_status: sensor.tarantulapro_print_status
      print_state: binary_sensor.tarantulapro_printing
      printhead_temp: sensor.tarantulapro_tool_0_temperature
      octoprint_shutdown: button.tarantulapro_shutdown_system
      safe_shutdown: button.tarantulapro_cancel_print
