- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_ccw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_cw_face_4:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.test_color
      scene_rotate_ccw_face_4:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.test_color
      action_flip_from_any_to_face_2: []