- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - action: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.jennys_room_display
      action_throw:
      - action: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.jennys_room_display
      action_rotate_ccw_face_6:
      - action: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - action: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.jennys_room_display
      scene_rotate_ccw_face_3:
      - action: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.jennys_room_display
      scene_rotate_cw_face_4:
      - action: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.test_color
      scene_rotate_ccw_face_4:
      - action: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.test_color
      action_flip_from_any_to_face_2: []
- id: '1733339152395'
  alias: test of dryer current sense
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.dryer_power_produced_energy
    attribute: current
    below: 0.05
  conditions: []
  actions:
  - action: script.tts_dryer_done
    data:
      live_speaker:
      - media_player.kitchen_speaker
  mode: single
- id: '1733964041898'
  alias: Party is over rodent
  description: Turns on the sonic screwdriver when Mom's light is off
  triggers:
  - trigger: state
    entity_id:
    - light.mom_light
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Wax on
  - trigger: state
    entity_id:
    - light.mom_light
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: wax off
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Wax on
      sequence:
      - action: switch.turn_on
        data: {}
        target:
          label_id: sonic_screwdriver
    default:
    - action: switch.turn_off
      data: {}
      target:
        label_id: sonic_screwdriver
  mode: single
- id: '1749576797273'
  alias: Suspend_Morning_AC
  description: Pause the AC in the morning if getting up early
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.suspend
    to: 'on'
    not_from:
    - unknown
    - unavailable
    id: Suspend
  - trigger: time
    at: 09:00:00
    id: Release
  conditions: []
  actions:
  - choose:
    - conditions:
      - alias: If the button was pushed and cooling is enabled & before alarm time
        condition: and
        conditions:
        - condition: trigger
          id:
          - Suspend
        - condition: state
          entity_id: input_boolean.bedroom_auto_fan
          state: 'on'
        - condition: time
          before: 08:58:18
      sequence:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.bedroom_auto_fan
        data: {}
    - conditions:
      - alias: If it's cooling season & after alarm time & suspend is on
        condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.gw2000b_v2_2_4_feels_like_temperature
          above: 42
        - condition: trigger
          id:
          - Release
        - condition: state
          entity_id: input_boolean.suspend
          state: 'on'
      sequence:
      - action: input_boolean.turn_on
        target:
          entity_id:
          - input_boolean.bedroom_auto_fan
        data: {}
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.suspend
        data: {}
    - conditions:
      - condition: time
        after: 08:58:21
      sequence:
      - action: input_boolean.turn_on
        target:
          entity_id:
          - input_boolean.bedroom_auto_fan
        data: {}
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.suspend
        data: {}
  mode: single
- id: '1759764035800'
  alias: aaaaaaatest Person Alert Monitor - 2024-06-08
  description: ''
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      zone2monitor:
      - zone.belva
      - zone.clinic
      - zone.nail_shop2
      - zone.elkhorn
      - zone.expo
      - zone.feed_store
      - zone.follicle_assembly_building
      - zone.home
      - zone.katy_s_kloset
      - zone.lakewood
      - zone.lindas_lair
      - zone.m_h_s_dream_society
      - zone.milstone
      - zone.moms_house
      - zone.suring
      - zone.townsend
      - zone.wisconsin_illinois_border
      - zone.somerhome
      - zone.shawano
      - zone.mountain
      - zone.piesler_ranch
      - zone.restoration_and_repair_facility
      - zone.retzer_nature_center
      - zone.rose_estate
      enter_action:
      - action: button.press
        metadata: {}
        data: {}
        target:
          entity_id: button.3a_smart_home_de_lxt56_ls27lx1_7_identify
      leave_action:
      - action: button.press
        metadata: {}
        data: {}
        target:
          entity_id: button.3a_smart_home_de_lxt56_ls27lx1_7_identify
      people2monitor:
      - person.julie
- id: '1759767251746'
  alias: aaaaaaaaaaaaaaaaaaaaaaaaaatest Person Alert Monitor - 2024-06-08
  description: ''
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      people2monitor:
      - person.jim
      enter_action:
      - action: button.press
        metadata: {}
        data: {}
        target:
          entity_id: button.3a_smart_home_de_lxt56_ls27lx1_7_identify
      zone2monitor: '{{ states.zone | map(attribute="entity_id") | list }}'
      leave_action: []
