- id: '1627278357461'
  alias: Door open tts.cloud_say announcer (Nabu-Casa required)
  description: testing one
  use_blueprint:
    path: SirGoodenough/door_open_tts_cloud_say_announcer_nabu_casa_required.yaml
    input:
      speaker_language: en-AU
      speaker_gender: male
      door_entity: binary_sensor.back_door_open_433
      speaker_target: media_player.hismart_tv
      announcement_message: This is the Day that the Lord hath made!
      final_message: The Devil is in the Details
      cooldown: 20
