- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - service: script.aaaaaaaaabbbbbtestvolume
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_ccw_face_3:
      - service: script.aaaaaaaaabbbbbtestvolume
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
- id: '1689973948504'
  alias: aaaaaaaaaaa office fan test
  description: testing tasmota 0123 speed ctrl
  use_blueprint:
    path: SirGoodenough/AutoFanControl_HA_fan.yaml
    input:
      fan_control: input_boolean.fan_test
      room_temp_now: sensor.lumi_lumi_sensor_cube_aqgl01_device_temperature
      room_set_temp: input_number.mayson_nap_temperature
      fan: fan.office_fan
      loop_action: []
      off_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.kitchensink
- id: '1690133105124'
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.74
    target:
      entity_id: media_player.kitchen_speaker
  mode: single
