- id: '1670436663509'
  alias: Broadlink or Luton is Down
  description: Testing new blueprint
  use_blueprint:
    path: SirGoodenough/pfsense_device_tracker.yaml
    input:
      trackees:
      - device_tracker.rassilon_mountcadon_duckdns_org_c8_f7_42_21_a6_a8_2
      - device_tracker.luton
      - device_tracker.luton_mountcadon_duckdns_org_00_0e_0c_5e_9a_8c
