- id: '1650188032017'
  alias: M-RM02 Controller - 2a
  description: ''
  use_blueprint:
    path: test/z2mTest.yaml
    input:
      remote: sensor.mom_button_action
      tap_2:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.growlight2
