- id: '1670436663509'
  alias: Drall is Down
  description: Testing new blueprint
  use_blueprint:
    path: SirGoodenough/Device_tracker Monitor & Notifier.yaml
    input:
      trackees:
      - device_tracker.rassilon_mountcadon_duckdns_org_dc_a6_32_a0_43_e7_2
      - device_tracker.rassilon_mountcadon_duckdns_org_dc_a6_32_a0_43_e6_2
      alt_notify:
      - service: script.say_a_thing
        data:
          message: Drall is DOWN. Ping the big boned guy.
          entities: media_player.kitchen_speaker
