- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - action: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.jennys_room_display
      action_throw:
      - action: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.jennys_room_display
      action_rotate_ccw_face_6:
      - action: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - action: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.jennys_room_display
      scene_rotate_ccw_face_3:
      - action: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.jennys_room_display
      scene_rotate_cw_face_4:
      - action: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.test_color
      scene_rotate_ccw_face_4:
      - action: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.test_color
      action_flip_from_any_to_face_2: []
- id: '1733339152395'
  alias: test of dryer current sense
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.dryer_power_produced_energy
    attribute: current
    below: 0.05
  conditions: []
  actions:
  - action: script.tts_dryer_done
    data:
      live_speaker:
      - media_player.kitchen_speaker
  mode: single
- id: '1733964041898'
  alias: Party is over rodent
  description: Turns on the sonic screwdriver when Mom's light is off
  triggers:
  - trigger: state
    entity_id:
    - light.mom_light
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Wax on
  - trigger: state
    entity_id:
    - light.mom_light
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: wax off
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Wax on
      sequence:
      - action: switch.turn_on
        data: {}
        target:
          entity_id: switch.sonic_screwdriver
    default:
    - action: switch.turn_off
      data: {}
      target:
        entity_id: switch.sonic_screwdriver
  mode: single
