- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.test_color
- id: '1676934491362'
  alias: AAAAApresence
  description: shssbheh25gwbbw  vs x
  use_blueprint:
    path: test/Person_alert_Blueprint.yaml
    input:
      people2monitor:
      - person.julie
      zone2monitor:
      - zone.katy_s_kloset
      enter_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.cabinetlight
      - service: script.turn_on
        target:
          entity_id: script.personalert
        data:
          variables:
            people: person.julie
            place: zone.katy_s_kloset
            trigg: enter_trigger
            notify_id: c26746c99ae2
      leave_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.cabinetlight
      - service: script.turn_on
        target:
          entity_id: script.personalert
        data:
          variables:
            people: person.julie
            place: zone.katy_s_kloset
            trigg: leave_trigger
            notify_id: c26746c99ae2

