- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_ccw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
- id: '1692033269574'
  alias: aaaaaaaa test door
  description: add voice to door test
  use_blueprint:
    path: SirGoodenough/door_open_tts_cloud_say_announcer_nabu_casa_required.yaml
    input:
      door_entity:
      - binary_sensor.back_door_open_433
      start_time: 08:00:00
      end_time: '22:00:00'
      speaker_target:
      - media_player.kitchen_speaker
      speaker_gender: male
      speaker_language: en-US
      cooldown: 120
      speaker_voice: '{{ ("JennyNeural", "AIGenerate1Neural", "AIGenerate2Neural",
        "AmberNeural", "AnaNeural", "AriaNeural", "AshleyNeural", "BrandonNeural",
        "ChristopherNeural", "CoraNeural", "DavisNeural", "ElizabethNeural", "EricNeural",
        "GuyNeural", "JacobNeural", "JaneNeural", "JasonNeural", "JennyMultilingualNeural",
        "MichelleNeural", "MonicaNeural", "NancyNeural", "RogerNeural", "SaraNeural",
        "SteffanNeural", "TonyNeural") | random }}'
      final_message: Thank you for closing the {{("rocket", "outhouse", "Audi", "rectory",
        "barn", "chicken coops", "van down by the rivers", "Walmart", "amazon", "fish
        shantys", "workshop", "monistary", "bee hive", "bird cage", "freezer", "refrigerator",
        "vacuum chambers", "emergency room", "dumpster", "manure pits", "spa", "heavens",
        "bistro", "candy factory", "garage") | random }} door.
      announcement_message: Your {{("rocket", "outhouse", "Audi", "rectory", "barn",
        "chicken coops", "van down by the rivers", "Walmart", "amazon", "fish shantys",
        "workshop", "monistary", "bee hive", "bird cage", "freezer", "refrigerator",
        "vacuum chambers", "emergency room", "dumpster", "manure pits", "spa", "heavens",
        "bistro", "candy factory", "garage") | random }} door has been left open.
