- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_ccw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_cw_face_4:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.test_color
      scene_rotate_ccw_face_4:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.test_color
      action_flip_from_any_to_face_2: []
- id: '1696495980412'
  alias: Cold Storage Door Monitor
  description: Warn if the Kitchen Fridge/Freezer or the Porch Freezer has been left
    open.
  use_blueprint:
    path: SirGoodenough/door_open_tts_cloud_say_and_Piper_announcer_Piper_OR_nabu_casa_required.yaml
    input:
      door_entity:
      - binary_sensor.kitchen_fridge_open_433
      - binary_sensor.kitchen_freezer_open_433
      - binary_sensor.porch_freezer_open_433
      reminded: input_boolean.cold_reminded
      speaker_target:
      - media_player.kitchen_speaker
      - media_player.garage_speaker
      - media_player.living_room_speaker
      - media_player.workroom_speaker
      - media_player.office_speaker_1
      - media_player.basement_speaker
      piper_voice: '{{("en_US-lessac-medium","en_US-amy-low","en_US-amy-medium","en_US-arctic-medium","en_US-danny-low","en_US-joe-medium","en_US-kathleen-low","en_US-kusal-medium","en_US-l2arctic-medium","en_US-lessac-high","en_US-lessac-low","en_US-lessac-medium","en_US-libritts-high","en_US-libritts_r-medium","en_US-ryan-high","en_US-ryan-low","en_US-ryan-medium")|random}}'
      tts_service: piper
      announcement_message: Your {{ door }} has been left open.
      cooldown: 63
      final_message: Thank you for closing the {{ door }}.
      speaker_voice: '{{ ("JennyNeural", "AIGenerate1Neural", "AIGenerate2Neural",
        "AmberNeural", "AnaNeural", "AriaNeural", "AshleyNeural", "BrandonNeural",
        "ChristopherNeural", "CoraNeural", "DavisNeural", "ElizabethNeural", "EricNeural",
        "GuyNeural", "JacobNeural", "JaneNeural", "JasonNeural", "JennyMultilingualNeural",
        "MichelleNeural", "MonicaNeural", "NancyNeural", "RogerNeural", "SaraNeural",
        "SteffanNeural", "TonyNeural") | random }}'
- id: '1699644276218'
  alias: aaaaaKids flip the lights
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.kids_lights_action
  action:
  - service: script.random_color
    data:
      light:
        entity_id: light.grp_kitch
  initial_state: 'on'
  mode: restart
- id: '1705369884373'
  alias: CO2 Warning Level
  description: TTS to tell CO2 is high <1000 for 10 minutes
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.ethernettest_kitchen_co2
    above: 1000
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.intercom_group
      message: CO2 values are at an uncomfortable level. Please investigate. CO2 values
        are at an uncomfortable level. Please investigate.
  mode: single
- id: '1705372172058'
  alias: CO2 levels hazardous level
  description: Level is above 2000 ppm.
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.ethernettest_kitchen_co2
    above: 2000
  condition: []
  action:
  - service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.home_group
      message: Take immediate action.  Open doors. CO2 level is in the unsafe range.
        Take immediate action.  Open doors. CO2 level is in the unsafe range.
  mode: single
- id: '1705944329325'
  alias: Goodnight Alarm
  description: Play the QOTD at betdime
  trigger:
  - platform: time
    at: 02:00:21
  action:
  - service: script.qotd
  mode: single
