- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.test_color
- id: 7b24d93c-d092-48f9-838d-233746babc21
  alias: aaaaAAAaaaaAAacc Person Alert Honitor
  description: Alert when we go places
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Person_Alert_Blueprint.yaml
    input:
      people2monitor:
      - person.julie
      - person.jen
      - person.jim
      zone2monitor:
      - zone.home
      - zone.katy_s_kloset
      - zone.follicle_assembly_building
      - zone.feed_store
      - zone.nail_shop2
      - zone.belva
      - zone.clinic
      - zone.expo
      enter_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: enter
        - service: script.personalert_audio
          data:
            message: "{{ trigger.to_state.attributes.friendly_name + ' has
              arrived at ' + trigger.to_state.state }}\n"
            entities: media_player.intercom_group
      leave_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.from_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.from_state.context.id }}'
            phase: leave
        - service: script.personalert_audio
          data:
            message: "{{ trigger.from_state.attributes.friendly_name + ' has
              left ' + trigger.from_state.state }}\n"
            entities: media_player.intercom_group
      jump_action:
      - parallel:
        - service: script.personalert_notify
          data:
            person: '{{ trigger.to_state.attributes.friendly_name }}'
            place_to: '{{ trigger.to_state.state }}'
            place_from: '{{ trigger.from_state.state }}'
            notify_id: '{{ trigger.to_state.context.id }}'
            phase: jump
        - service: script.personalert_audio
          data:
            message: "{{ trigger.to_state.attributes.friendly_name + ' has
              left ' + trigger.from_state.state + ' and is located at: ' + 
              trigger.to_state.state }}"
            entities: media_player.intercom_group
  mode: parallel
