- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: script.cube_long_short_control_bp
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      scene_rotate_cw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_ccw_face_3:
      - service: script.volume4cube
        data:
          angle: '{{ trigger.payload_json.action_angle | default(0.1) | float(0.2)
            }}'
          mp: media_player.kitchen_speaker
      scene_rotate_cw_face_4:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.test_color
      scene_rotate_ccw_face_4:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.test_color
- id: '1696281099994'
  alias: aaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggDoor
    open tts.cloud_say announcer (Uses Piper Addon OR Nabu-Casa Cloud) - 2023-10-02-beta
  description: ''
  use_blueprint:
    path: test/TestDoorPiperBeta.yaml
    input:
      door_entity:
      - binary_sensor.back_door_open_433
      speaker_target:
      - media_player.kitchen_speaker
      speaker_gender: male
      speaker_language: en-US
      cooldown: 12
      speaker_voice: '{{ ("JennyNeural", "AIGenerate1Neural", "AIGenerate2Neural",
        "AmberNeural", "AnaNeural", "AriaNeural", "AshleyNeural", "BrandonNeural",
        "ChristopherNeural", "CoraNeural", "DavisNeural", "ElizabethNeural", "EricNeural",
        "GuyNeural", "JacobNeural", "JaneNeural", "JasonNeural", "JennyMultilingualNeural",
        "MichelleNeural", "MonicaNeural", "NancyNeural", "RogerNeural", "SaraNeural",
        "SteffanNeural", "TonyNeural") | random }}'
      final_message: Thank you for closing the {{("rocket", "outhouse", "Audi", "rectory",
        "barn", "chicken coops", "van down by the rivers", "Walmart", "amazon", "fish
        shantys", "workshop", "monistary", "bee hive", "bird cage", "freezer", "refrigerator",
        "vacuum chambers", "emergency room", "dumpster", "manure pits", "spa", "heavens",
        "bistro", "candy factory", "garage") | random }} door.
      announcement_message: Your {{("rocket", "outhouse", "Audi", "rectory", "barn",
        "chicken coops", "van down by the rivers", "Walmart", "amazon", "fish shantys",
        "workshop", "monistary", "bee hive", "bird cage", "freezer", "refrigerator",
        "vacuum chambers", "emergency room", "dumpster", "manure pits", "spa", "heavens",
        "bistro", "candy factory", "garage") | random }} door has been left open.
      reminded: input_boolean.reminded
      tts_service: piper
      piper_voice: '{{ ("en_US-lessac-medium","en_US-amy-low","en_US-amy-medium","en_US-arctic-medium","en_US-danny-low","en_US-joe-medium","en_US-kathleen-low","en_US-kusal-medium","en_US-l2arctic-medium","en_US-lessac-high","en_US-lessac-low","en_US-lessac-medium","en_US-libritts-high","en_US-libritts_r-medium","en_US-ryan-high","en_US-ryan-low","en_US-ryan-medium")
        | random }}'

