- id: '1674709536293'
  alias: aaaaattesttT1-Pro-(CTP-R01)
  description: testing
  trace:
    stored_traces: 10
  use_blueprint:
    path: SirGoodenough/Zigbee2MQTT-Aqara-Magic-Cube-T1-Pro-CTP-R01-Xiaomi-Lumi.yaml
    input:
      topic: zigbee2mqtt/testcagl02
      scene_throw:
      - service: script.say_a_thing
        data:
          message: Scene Throw
          entities: media_player.kitchen_speaker
      action_throw:
      - service: script.say_a_thing
        data:
          message: Action Throw
          entities: media_player.kitchen_speaker
      action_rotate_ccw_face_6:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.test_color
- id: '1676934491362'
  alias: AAAAApresence
  description: shssbheh25gwbbw  vs x
  use_blueprint:
    path: test/Person_alert_Blueprint.yaml
    input:
      people2monitor:
      - person.julie
      zone2monitor:
      - zone.katy_s_kloset
      enter_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.cabinetlight
      - service: script.personalert
        data:
          people: '{{ trigger.to_state.attributes.friendly_name }}'
          trigg: '{{ trigger.id }}'
          notify_id: '{{ trigger.to_state.context.id }}'
          place: '{% if trigger.zone is defined %} {{ trigger.zone.attributes.friendly_name
            }} {% else %} No Zone Defined {% endif %}'
      leave_action:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.cabinetlight
      - service: script.personalert
        data:
          people: '{{ trigger.to_state.attributes.friendly_name }}'
          trigg: '{{ trigger.id }}'
          notify_id: '{{ trigger.to_state.context.id }}'
          place: '{% if trigger.zone is defined %} {{ trigger.zone.attributes.friendly_name
            }} {% else %} No Zone Defined {% endif %}'
- id: '1677177444493'
  alias: aaaaaaaaaaaaaaaaaaaaaaabtest zone
  description: 'gej567ik4etbryd,kfymyj 678k6 6 t '
  trigger:
  - platform: state
    entity_id:
    - person.julie
  condition:
  - condition: zone
    entity_id: person.julie
    zone: zone.katy_s_kloset
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.kitchen_down_lights
  mode: single
