- id: '1626335294896'
  alias: Keypad 5 button cypher to turn on something
  description: AAAaaa  Test 44 KeyPad
  use_blueprint:
    path: Sir_Goodenough/keypad-cypher-code-for-5-button-presses-before-you-turn-on-an-input-boolean.yaml
    input:
      button_one: binary_sensor.pad_1
      button_two: binary_sensor.pad_2
      button_three: binary_sensor.pad_3
      button_four: binary_sensor.pad_4
      button_five: binary_sensor.pad_5
      lock_control: input_boolean.pad_enable
      seq_status: input_number.lock_state
