- id: '1652244525468'
  alias: "Mayson's Naptime Auto Fan"
  description: 'Set the Temperature for Naptime 11am 4:30pm'
  use_blueprint:
    path: SirGoodenough/AutoFanControl.yaml
    input:
      fan_off_time: 04:31:18
      fan_control: input_boolean.mayson_cool
      room_set_temp: input_number.mayson_nap_temperature
      room_temp_now: sensor.bedroom_fan_si7021_temperature
      fan_on_time: 11:11:11
      mqtt_fan_topic: Bedroom_Fan/cmnd/FanSpeed
      loop_action:
      - alias: call bedroom ac start script
        if: '{{ states(''climate.gemodule5384'') == ''off'' }}'
        then:
          service: script.bedroom_ac_start
      - alias: "call Mayson ac set temperature & limit to prevent rate limit outages"
        if: '{{ is_number(state_attr(''climate.gemodule5384'', ''temperature''))
          and state_attr(''climate.gemodule5384'', ''temperature'') | float(73.1)
          != states(''input_number.mayson_nap_temperature'') | float(73.1) }}'
        then:
          service: script.bedroom_ac_set_temp
          data:
            Temp: '{{ states(''input_number.mayson_nap_temperature'') | float(73.1) }}'
      off_action:
      - alias: call shut the AirCon down script
        service: script.bedroom_cooling_off
