# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

# Individual options represented by default_config
automation: !include automations.yaml
automation manual: !include_dir_merge_list ./automation2/
automation dev: !include_dir_merge_list ./automationDev/
# backup:
bluetooth:
cloud: !include cloud.yaml
config:
counter: !include counter.yaml
dhcp:
# energy
frontend: !include frontend.yaml
history: !include history.yaml
image:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
media_source: !include media.yaml
# mobile_app:
my:
person: !include person.yaml
scene: !include scene.yaml
script: !include_dir_merge_named ./script2/
ssdp:
stream:
sun:
system_health:
# tag:
timer: !include timer.yaml
usb:
webhook:
zeroconf:
zone:

# All the other stuff not covered in the default_config:

# binary_sensor: !include_dir_merge_list ./binSensor/
# button: !include button.yaml
conversation:
# cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
# fan: !include fan.yaml
ffmpeg: !include ffmpeg.yaml
generic_hygrostat: !include humidifer.yaml
group: !include groups.yaml
hacs: !include hacs.yaml
homeassistant: !include homeassistant.yaml
http: !include http.yaml
# introduction:
# life360: !include life360.yaml
light: !include_dir_merge_list ./light/
# lock: !include lock.yaml
logger: !include logger.yaml
notify: !include notify.yaml
# mqtt: !include_dir_merge_named ./mqtt/
mqtt:
  binary_sensor: !include_dir_merge_list mqtt/binary_sensor/
  button: !include_dir_merge_list mqtt/button/
  cover: !include_dir_merge_list mqtt/cover/
  fan: !include_dir_merge_list mqtt/fan/
  light: !include_dir_merge_list mqtt/light/
  lock: !include_dir_merge_list mqtt/lock/
  sensor: !include_dir_merge_list mqtt/sensor/
  switch: !include_dir_merge_list mqtt/switch/
panel_custom: !include panel_custom.yaml
panel_iframe: !include panel_iframe.yaml
python_script:
recorder: !include recorder.yaml
remote_command_line: !include remote_cmd.yaml
rest_command: !include rest_command.yaml
ring: !include ring.yaml
sensor: !include_dir_merge_list ./sensor2/
shell_command: !include shell_command.yaml
sonoff: !include sonoff.yaml
switch: !include switch.yaml
switch two: !include_dir_merge_list ./switch2/
template: !include_dir_merge_list ./templates/
tts: !include tts.yaml
webhook_service:
