alert: !include alert.yaml
automation: !include automations.yaml
automation manual: !include_dir_merge_list ./automation2
automation dev: !include_dir_merge_list ./automationDev
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
# climate: !include climate.yaml
cloud: !include cloud.yaml
config:
conversation:
counter: !include counter.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
dhcp:
fan: !include fan.yaml
ffmpeg: !include ffmpeg.yaml
frontend: !include frontend.yaml
group: !include groups.yaml
hacs: !include hacs.yaml
homeassistant: !include homeassistant.yaml
history: !include history.yaml
http: !include http.yaml
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
# introduction:
life360: !include life360.yaml
light: !include light.yaml
lock: !include lock.yaml
logbook:
logger: !include logger.yaml
map:
my:
notify: !include notify.yaml
octoprint: !include octoprint.yaml
person: !include person.yaml
panel_custom: !include panel_custom.yaml
panel_iframe: !include panel_iframe.yaml
python_script:
recorder: !include recorder.yaml
rest_command: !include rest_command.yaml
ring: !include ring.yaml
# script: !include scripts.yaml
script: !include_dir_merge_named ./script2
sensor: !include sensors.yaml
sonoff: !include sonoff.yaml
sun:
system_health:
switch: !include switch.yaml
switch two: !include_dir_merge_list ./switch2
timer: !include timer.yaml
tts: !include tts.yaml
#updater: !include updater.yaml
zwave: !include zwave.yaml
