blueprint:
  author: Didgeridrew
  homeassistant:
    min_version: 2025.5.0
  name: Weekday Sensor
  description: Creates a sensor which holds a value related to the current weekday.
  domain: template
  input:
    weekday_names:
      name: Weekday Names
      description: 'If you want the names in a language other than English, or you
        want to use abbreviations, list them from Monday to Sunday.

        '
      selector:
        text:
          multiple: true
          multiline: false
      default: '{{[''Monday'',''Tuesday'',''Wednesday'',''Thursday'',''Friday'',''Saturday'',''Sunday'']}}

        '
  source_url: https://community.home-assistant.io/t/weekday-name-sensor/887126
variables:
  weekday_names: !input weekday_names
trigger:
- trigger: homeassistant
  event: start
- trigger: time_pattern
  hours: /12
sensor:
  state: '{{ weekday_names[now().weekday()] }}'
  availability: '{{true}}'
