blueprint:
  name: MQTTCarPresence
  description: Open garage door when car connects to Wi-Fi
  domain: automation
  input:
    garage_door:
      name: Garage Door
      description: This light for test
      selector:
        entity:
          domain: light
    car_presence:
      name: Car Presence
      description: This sensor is the car's connection to the MQTT broker
      selector:
        entity:
          domain: switch
  source_url: https://raw.githubusercontent.com/aderusha/MQTTCarPresence/master/MQTTCarPresence.yaml
mode: single
trigger:
- platform: state
  entity_id: !input 'car_presence'
  to: 'on'
- platform: state
  entity_id: !input 'car_presence'
  to: 'off'
  for:
    minutes: 1
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input 'car_presence'
      state: 'on'
    - condition: state
      entity_id: !input 'garage_door'
      state: 'off'
    sequence:
    - service: light.turn_on
      entity_id: !input 'garage_door'
  - conditions:
    - condition: state
      entity_id: !input 'car_presence'
      state: 'off'
    - condition: state
      entity_id: !input 'garage_door'
      state: 'on'
    sequence:
    - service: light.turn_off
      entity_id: !input 'garage_door'
  default: []
