binary_sensor:
  #####################################################
  # DoorBell                                          #
  #####################################################

  - name: "Side Doorbell"
    unique_id: 51f99488-996b-4133-aafc-11e2d9562154
    state_topic: rf433/SideDoorBell
    payload_on: 'ON'
    payload_off: 'OFF'
    off_delay: 3
    availability_topic: RFBridge2/tele/LWT
    payload_available: Online
    payload_not_available: Offline
