blueprint:
  name: Auto_Fan_Temperature_Control_for_3-Speed_Fan_HA_fan_2022-05-15
  description: 'This sets the fan speed for a 3 speed fan (such as an IFAN03/IFAN04)
    based on a room temperature.


    In fact any fan with 3 speeds that is connected to the HA Fan Integration will
    work with this blueprint.


    ***NOTE:*** See the [Sister Blueprint](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/AutoFanControl_MQTT.yaml)
    if you want to create an automation using MQTT.


    if you want to control this fan using the Home Assistant Fan Integration instead.


    There are action selectors for both the cycle loop and the shutdown loop for adding
    control of heating / cooling sources, or anything else you want Home Assistant
    to do for you.


    [Community link for this blueprint](https://community.home-assistant.io/t/auto-fan-temperature-control-for-3-speed-fan-ifanxx-tasmota/326419)'
  source_url: https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/AutoFanControl%20HA_fan.yaml
  domain: automation
  homeassistant:
    min_version: 2022.5.2
  input:
    fan_control:
      name: Toggle to turn the fan function off for when away or seasonally
      description: '(#1) ```input_boolean``` - If this is set to off, the Automation
        will be disabled.

        This Helper has to be set up in [![Open your Home Assistant instance and show
        your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/) '
      selector:
        entity:
          domain: input_boolean
          multiple: false
    room_temp_now:
      name: Room Temperature Sensor
      description: '(#2) This is a temperature sensor or averaged temperature sensor
        preferrably within the path of the moving air from the fan.

        Otherwise the action will be laggy where changes in temperature will have
        a lower effect on fan speed.'
      selector:
        entity:
          domain: sensor
          multiple: false
    room_set_temp:
      name: Room Target Temperature
      description: '(#3) ```input_number``` - This is the target temperature of the
        room.

        This can be Metric or imperial, but the same scale as the temperature sensor.

        This Helper has to be set up in [![Open your Home Assistant instance and show
        your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/) '
      selector:
        entity:
          domain: input_number
          multiple: false
    temp_gap:
      name: Temp Hysteresis
      description: '(#4) This keeps the fan from speed cycling too often. (Let''s
        call it Hysterisis)

        Set it bigger if the fan goes on and off too much.

        Set it smaller if the fan doesn''t change speeds fast enough.

        0 is a good number if this area is not used in conjunction with a heating
        or cooling unit where you want to set them both to 21C (for instance).

        I use the Temperature setting input_number as an input to climate and this
        at the same time, so I needed an offset.

        My AirCon (or a heat source) is triggered using the 2 action sensors provived.
        See examples in the [Documentation Here](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/AutoFanControl.md) '
      default: 1.3
      selector:
        number:
          min: 0.0
          max: 7.0
          unit_of_measurement: Degrees
          mode: slider
          step: 0.1
    temp_gap_1_to_2:
      name: Temp Gap between Low and Medium
      description: '(#5) This is the temp swing between Low and Medium.

        If the sensor reads between the base temperature and this number of degrees
        warmer, the fan is on LOW.

        Below the base temperature the fan is off.'
      default: 4.5
      selector:
        number:
          min: 1.0
          max: 20.0
          unit_of_measurement: Degrees
          mode: slider
          step: 0.1
    temp_gap_2_to_3:
      name: Temp Gap between Medium and High
      description: '(#6) This is the temp change between Medium and High.

        If the sensor reads between the base temperature plus the 1 to 2 temperature
        and this number of degrees warmer, the fan is on MEDIUM.

        Any warmer than this and the fan is set to HIGH.'
      default: 2.0
      selector:
        number:
          min: 1.0
          max: 20.0
          unit_of_measurement: Degrees
          mode: slider
          step: 0.1
    fan_on_time:
      name: Time of day fan should start
      description: (#7) Set this for the time of day you want the fan function to
        be enabled.
      selector:
        time: {}
    fan_off_time:
      name: Time of day fan should stop
      description: (#8) Set this for the time of day you want the fan function to
        end.
      selector:
        time: {}
    weekday:
      name: Day of the week to use the Automation
      description: (#9)
      default:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          custom_value: false
          multiple: true
    fan:
      name: Fan Entity
      description: (#10) This is the Home Assistant Fan entity
      selector:
        entity:
          domain: fan
          multiple: false
    loop_action:
      name: User action for fan enabled condition (loop)
      description: '(#11) This is intended to start / set temp on an AC unit or whatever
        you want to do. It is executed on every successful trigger that does not send
        the operation to off.

        See the [Example](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/AutoFanControl.md)
        that is added as YAML mode here.

        Leave it empty to do nothing extra.'
      default: []
      selector:
        action: {}
    off_action:
      name: User action for fan off condition (off_action)
      description: '(#12) This is intended to disable an AirCon unit or whatever you
        want to do. It is executed on every successful operation off trigger.

        See the [Example](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/AutoFanControl.md)
        that is added as YAML mode here.

        Leave it empty to do nothing extra.'
      default: []
      selector:
        action: {}
variables:
  temp_gap_var: !input 'temp_gap'
  temp_gap_val: '{{ temp_gap_var | float(0.0) }}'
  temp_gap_1_to_2_var: !input 'temp_gap_1_to_2'
  temp_gap_1_to_2_val: '{{ temp_gap_1_to_2_var | float(0.0) }}'
  temp_gap_2_to_3_var: !input 'temp_gap_2_to_3'
  temp_gap_2_to_3_val: '{{ temp_gap_2_to_3_var | float(0.0) }}'
  room_temp_now_var: !input 'room_temp_now'
  room_temp_now_val: '{{ expand(room_temp_now_var)[0].state | float(0.0) }}'
  room_set_temp_var: !input 'room_set_temp'
  room_set_temp_val: '{{ expand(room_set_temp_var)[0].state | float(0.0) - temp_gap_val
    | float(0) }}'
  my_loop_action: !input 'loop_action'
  my_off_action: !input 'off_action'
mode: restart
trigger:
- platform: time
  id: go_if_the_stop_time_occurs
  at: !input 'fan_off_time'
- platform: state
  id: go_if_the_control_is_switched_off
  entity_id: !input 'fan_control'
  to: 'off'
- platform: state
  id: go_on_any_sensor_temp_changes
  entity_id: !input 'room_temp_now'
- platform: state
  id: go_on_any_set_temp_changes
  entity_id: !input 'room_set_temp'
- platform: time
  id: go_if_the_start_time_occurs
  at: !input 'fan_on_time'
- platform: state
  id: go_if_the_control_is_switched_on
  entity_id: !input 'fan_control'
  to: 'on'
action:
- choose:
  - alias: Fan normal turn off sequence
    conditions:
      or:
      - alias: Time limit has been reached
        condition: trigger
        id: go_if_the_stop_time_occurs
      - alias: The automation has been disabled
        condition: trigger
        id: go_if_the_control_is_switched_off
    sequence:
    - alias: Do something when the fan stop condition triggers
      if: '{{ not my_off_action in (''none'', ''null'', ''unavailable'', '''') }}'
      then: !input 'off_action'
    - alias: Stop the fan
      service: fan.turn_off
      target:
        entity_id: !input 'fan'
  - alias: Normal fan run sequence
    conditions:
      and:
      - alias: Make sure the Fan is enabled
        condition: state
        entity_id: !input 'fan_control'
        state: 'on'
      - alias: Only allow execution within selected Hours / Weekdays
        condition: time
        after: !input 'fan_on_time'
        before: !input 'fan_off_time'
        weekday: !input 'weekday'
    sequence:
    - alias: Do something on every fan set speed condition trigger
      if: '{{ not my_loop_action in (''none'', ''null'', ''unavailable'', '''') }}'
      then: !input 'loop_action'
    - alias: Set the fan speed based on the sensor temperature
      service: fan.set_percentage
      target:
        entity_id: !input 'fan'
      data:
        percentage: >-
          {% if room_temp_now_val < room_set_temp_val %}
          {# Room is cooler than set temp so turn fan OFF. #}
            0

          {% elif room_temp_now_val < (room_set_temp_val + temp_gap_1_to_2_val) %}
          {# Room is at the temp where the fan should be at LOW speed. #}
            33

          {% elif room_temp_now_val < (room_set_temp_val + temp_gap_1_to_2_val + temp_gap_2_to_3_val) %} 
          {# Room is at the temp where the fan should be at MEDIUM speed. #}
            66

          {% else %} 
          {# Room is warm enough to be on HIGH speed, #}
            100

          {% endif %}