blueprint:
  name: Door open tts.cloud_say announcer (Nabu-Casa required) - 2023-08-07
  author: SirGoodenough
  description: >
    This uses tts.cloud_say from Nabu-Casa to tell you a door is open too
    long and a door has been closed.

    📩 There is not an official version control system for Blueprints. However I have
    found something that comes pretty close. It is not perfect, but for **MOST**
    Blueprints, it does just fine. I encourage you to check this script out and use
    it to easily check if I have updated this blueprint. 🔗 [koter84 Blueprint Update Script](https://github.com/koter84/HomeAssistant_Blueprints_Update/)


    [Community link for this blueprint](https://community.home-assistant.io/t/door-open-tts-cloud-say-announcer-nabu-casa-required/316046)
#  source_url: https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/door_open_tts_cloud_say_announcer_nabu_casa_required.yaml
  homeassistant:
    min_version: 2023.8.0
  domain: automation
  input:
    door_entity:
      name: 'Door Sensor (or any binary_sensor will do...)'
      description: >
        Entity that initiates the announcement. Actually any entity that changes
        its state from off to on will work here, You would just need to enter the
        entity manually if it's not a binary sensor.
        However this BP is expecting 'on' or 'off' as the available states.
      selector:
        entity:
          multiple: true
          filter:
            - domain: binary_sensor
    start_time:
      name: StartTime
      description: >
        Time of day you want to enable the announcement each day.


        Leave at 12:00:00 if you want it to always be on.
      selector:
        time: {}
      default: 00:00:00
    end_time:
      name: EndTime
      description: >
        Time of day you want to disable the announcement each day. 


        Leave at 12:00:00 if you want it to always be on.
      selector:
        time: {}
      default: 00:00:00
    weekday:
      name: Day of the week to use the Automation
      description: >
        Day(s) of the week you want to enable the announcement. 


        Leave at default all selected if you want it to always be on.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          custom_value: false
          multiple: true
    speaker_target:
      name: Speaker
      description: Entity to announce event on
      selector:
        entity:
          filter:
            - domain: media_player
          multiple: true
    speaker_gender:
      name: Speaker Gender
      description: Select speaker gender male or female
      default: female
      selector:
        select:
          options:
          - female
          - male
          custom_value: false
          multiple: false
    speaker_language:
      name: Speaker Language
      description: >
        Select Language code. [See here for Details](https://www.nabucasa.com/config/tts/)

        This defaults to en-US (english/US). However all the languages available on
        2023-8-17 were put into the pick list. 


        ***NOTE: It is possible that not all Languages will give you both Genders.***
      default: en-US
      selector:
        select:
          options:
            - af-ZA
            - am-ET
            - ar-AE
            - ar-BH
            - ar-DZ
            - ar-EG
            - ar-IL
            - ar-IQ
            - ar-JO
            - ar-KW
            - ar-LB
            - ar-LY
            - ar-MA
            - ar-OM
            - ar-PS
            - ar-QA
            - ar-SA
            - ar-SY
            - ar-TN
            - ar-YE
            - az-AZ
            - bg-BG
            - bn-IN
            - bs-BA
            - ca-ES
            - cs-CZ
            - cy-GB
            - da-DK
            - de-AT
            - de-CH
            - de-DE
            - el-GR
            - en-AU
            - en-CA
            - en-GB
            - en-GH
            - en-HK
            - en-IE
            - en-IN
            - en-KE
            - en-NG
            - en-NZ
            - en-PH
            - en-SG
            - en-TZ
            - en-US
            - en-ZA
            - es-AR
            - es-BO
            - es-CL
            - es-CO
            - es-CR
            - es-CU
            - es-DO
            - es-EC
            - es-ES
            - es-GQ
            - es-GT
            - es-HN
            - es-MX
            - es-NI
            - es-PA
            - es-PE
            - es-PR
            - es-PY
            - es-SV
            - es-US
            - es-UY
            - es-VE
            - et-EE
            - eu-ES
            - fa-IR
            - fi-FI
            - fil-PH
            - fr-BE
            - fr-CA
            - fr-CH
            - fr-FR
            - ga-IE
            - gl-ES
            - gu-IN
            - he-IL
            - hi-IN
            - hr-HR
            - hu-HU
            - hy-AM
            - id-ID
            - is-IS
            - it-CH
            - it-IT
            - ja-JP
            - jv-ID
            - ka-GE
            - kk-KZ
            - km-KH
            - kn-IN
            - ko-KR
            - lo-LA
            - lt-LT
            - lv-LV
            - mk-MK
            - ml-IN
            - mn-MN
            - mr-IN
            - ms-MY
            - mt-MT
            - my-MM
            - nb-NO
            - ne-NP
            - nl-BE
            - nl-NL
            - pl-PL
            - ps-AF
            - pt-BR
            - pt-PT
            - ro-RO
            - ru-RU
            - si-LK
            - sk-SK
            - sl-SI
            - so-SO
            - sq-AL
            - sr-RS
            - sv-SE
            - sw-KE
            - sw-TZ
            - ta-IN
            - te-IN
            - th-TH
            - tr-TR
            - uk-UA
            - uz-UZ
            - vi-VN
            - wuu-CN
            - yue-CN
            - zh-CN
            - zh-CN-shandong
            - zh-CN-sichuan
            - zh-HK
            - zh-TW
            - zu-ZA
          custom_value: false
          multiple: false
    speaker_voice:
      name: Voice of the speaker
      description: >  
        ***Here you need to be careful.***

        If you are OK with the default voice then just leave this field empty.

        If you want to change the voice, you need to pick from [This List, TTS_VOICES section](https://github.com/NabuCasa/hass-nabucasa/blob/master/hass_nabucasa/voice.py)
        being certain to match the country code you picked above with one of
        the voices available for that country code on that list.

        Failure to do so will result in no voice being heard.


        Also picking a voice here results in your pick for Gender to be ignored.

        If you want to know what these sound like, well, you are just going to
        have to try them and see what you like.

        If you are en-US, you might want to paste this in there for some fun:

          {{ ("JennyNeural",
          "AIGenerate1Neural",
          "AIGenerate2Neural",
          "AmberNeural",
          "AnaNeural",
          "AriaNeural",
          "AshleyNeural",
          "BrandonNeural",
          "ChristopherNeural",
          "CoraNeural",
          "DavisNeural",
          "ElizabethNeural",
          "EricNeural",
          "GuyNeural",
          "JacobNeural",
          "JaneNeural",
          "JasonNeural",
          "JennyMultilingualNeural",
          "MichelleNeural",
          "MonicaNeural",
          "NancyNeural",
          "RogerNeural",
          "SaraNeural",
          "SteffanNeural",
          "TonyNeural") | random }}
      default: []
      selector:
        text:
          multiline: true
    announcement_message:
      name: Announcement message
      description: >  
        What to say when door is opened

        This can be set to "" if you do not want a message while sensor is active.
      default: Your Barn Door has been left open.
      selector:
        text:
          multiline: true
    final_message:
      name: Final message
      description: >
        What to say when door is closed.

        This can be set to "" if you do not want a message after the sensor is reset.
      default: Thank you for closing the barn door.
      selector:
        text:
          multiline: true
    cooldown:
      name: Announcement cooldown
      description: >
        The minimum number of seconds needed before AND between between
        announcements.

        This is your initial delay and pause between messages...
      default: 10
      selector:
        number:
          min: 4.0
          max: 7200.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    additional_conditions:
      name: Additional conditions
      description: |
        Extra conditions you may want to add to this automation 
        (Example: Home occupied, TV on, etc)
      default: []
      selector:
        condition:

trigger:
  platform: state
  entity_id: !input door_entity
  from: 'off'
  to: 'on'

condition:
  - alias: Only allow execution within selected Hours / Weekdays
    condition: time
    after: !input start_time
    before: !input end_time
    weekday: !input weekday
  - alias: User pick
    condition: !input additional_conditions

action:
- variables:
      # Convert !inputs to variables
    cooldown: !input cooldown
    doorS: !input door_entity

- alias: Repeat the sequence UNTIL the door is closed
  repeat:
    sequence:
    - alias: This is the delay broke into 2 sec incr so it can be interupted.
      repeat:
        while:
          - condition: state
            entity_id: !input door_entity
            state: "on"
          - condition: template
            value_template: "{{ repeat.index < cooldown/2 }}"
        sequence:
          - delay: 00:00:02
    - alias: Send announcement message (potentially again)
      if: 
      - condition: state
        entity_id: !input door_entity
        state: "on"
      then:
      - service: tts.cloud_say
        data:
          entity_id: !input speaker_target
          message: !input announcement_message
          options:
            gender: !input speaker_gender
            voice: !input speaker_voice
          language: !input speaker_language
      - alias: Delay to make sure the message can complete.
        delay: 00:00:10
    until:
    - condition: state
      entity_id: !input door_entity
      state: 'off'
- alias: Always try to say thanks at the end. Leave message empty for quiet
  service: tts.cloud_say
  data:
    entity_id: !input speaker_target
    message: !input final_message
    options:
      gender: !input speaker_gender
      voice: !input speaker_voice
    language: !input speaker_language

mode: queued
max: 10
max_exceeded: silent
