blueprint:
  name: Door open tts.cloud_say announcer (Nabu-Casa required) - 2023-03-01
  author: SirGoodenough
  description: 'This uses tts.cloud_say from Nabu-Casa to tell you a door is open too
    long and a door has been closed.

    📩 There is not an official version control system for Blueprints. However I have
    found something that comes pretty close. It is not perfect, but for **MOST**
    Blueprints, it does just fine. I encourage you to check this script out and use
    it to easily check if I have updated this blueprint. 🔗 [koter84 Blueprint Update Script](https://github.com/koter84/HomeAssistant_Blueprints_Update/)



    [Community link for this blueprint](https://community.home-assistant.io/t/door-open-tts-cloud-say-announcer-nabu-casa-required/316046)'
  source_url: https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/door_open_tts_cloud_say_announcer_nabu_casa_required.yaml
  homeassistant:
    min_version: 2023.3.0
  domain: automation
  input:
    door_entity:
      name: 'Door Sensor (or any binary_sensor will do...)'
      description: Entity that causes the announcement. Actually any entity that changes
        its state from off to on will work here, You would just need to enter the
        entity manually if it's not a binary sensor.
      selector:
        entity:
          multiple: true
          domain: binary_sensor
    start_time:
      name: StartTime
      description: 'Time of day you want to enable the announcement each day.


        Leave at 12:00:00 if you want it to always be on.'
      selector:
        time: {}
      default: 00:00:00
    end_time:
      name: EndTime
      description: 'Time of day you want to disable the announcement each day. 


        Leave at 12:00:00 if you want it to always be on.'
      selector:
        time: {}
      default: 00:00:00
    speaker_target:
      name: Speaker
      description: Entity to announce event on
      selector:
        entity:
          domain: media_player
          multiple: true
    speaker_gender:
      name: Speaker Gender
      description: Select speaker gender male or female
      default: female
      selector:
        select:
          options:
          - female
          - male
          custom_value: false
          multiple: false
    speaker_language:
      name: Speaker Language
      description: 'Select Language code. [See here for Details](https://www.nabucasa.com/config/tts/)

        This defaults to en-US (english/US). However all the languages available on
        2021-12-24 were put into the pick list. 


        ***NOTE: It is possible that not all Languages will give you both Genders.***'
      default: en-US
      selector:
        select:
          options:
          - ar-EG
          - ar-SA
          - bg-BG
          - ca-ES
          - zh-HK
          - zh-CN
          - zh-TW
          - hr-HR
          - cs-CZ
          - da-DK
          - nl-NL
          - en-AU
          - en-CA
          - en-IN
          - en-IE
          - en-GB
          - en-US
          - fi-FI
          - fr-CA
          - fr-FR
          - fr-CH
          - de-AT
          - de-DE
          - de-CH
          - el-GR
          - he-IL
          - hi-IN
          - hu-HU
          - id-ID
          - it-IT
          - ja-JP
          - ko-KR
          - ms-MY
          - nb-NO
          - pl-PL
          - pt-BR
          - pt-PT
          - ro-RO
          - ru-RU
          - sk-SK
          - sl-SI
          - es-MX
          - es-ES
          - sv-SE
          - ta-IN
          - te-IN
          - th-TH
          - tr-TR
          - vi-VN
          custom_value: false
          multiple: false
    announcement_message:
      name: Announcement message
      description: 'What to say when door is opened

        This can be set to "" if you do not want a message while sensor is active.'
      default: Your Barn Door has been left open.
    final_message:
      name: Final message
      description: 'What to say when door is closed.

        This can be set to "" if you do not want a message after the sensor is reset.'
      default: Thank you for closing the barn door.
    cooldown:
      name: Announcement cooldown
      description: 'The minimum number of seconds needed before AND between between
        announcements.

        This is your initial delay and pause between messages...'
      default: 10
      selector:
        number:
          min: 0.0
          max: 7200.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
mode: single
trigger:
  platform: state
  entity_id: !input 'door_entity'
  from: 'off'
  to: 'on'
condition:
  alias: Active time for the announcement
  condition: time
  after: !input 'start_time'
  before: !input 'end_time'
action:
- alias: Repeat the sequence UNTIL the door is closed
  repeat:
    sequence:
    - delay: !input 'cooldown'
    - service: tts.cloud_say
      data:
        entity_id: !input 'speaker_target'
        message: !input 'announcement_message'
        options:
          gender: !input 'speaker_gender'
        language: !input 'speaker_language'
    until:
    - condition: state
      entity_id: !input 'door_entity'
      state: 'off'
- service: tts.cloud_say
  data:
    entity_id: !input 'speaker_target'
    message: !input 'final_message'
    options:
      gender: !input 'speaker_gender'
    language: !input 'speaker_language'
