blueprint:
  name: MQTT_Tasmota_CarPresence
  description: Open garage door when car connects to Wi-Fi
  # Community link for blueprint:  source_url: 
  # https://community.home-assistant.io/t/ha-blueprint-to-use-tasmota-updated-esps-to-do-the-luma-car-presence-in-home-assistant-see-https-github-com-aderusha-mqttcarpresence-for-the-full-story/327717
  source_url: https://gist.github.com/SirGoodenough/f2fb094c399a2a308bc74938cb428716
  domain: automation
  input:
    garage_door:
      name: Garage Door
      description: This cover is the Garage Door
      selector:
        entity:
          domain: cover
    car_presence:
      name: Car Presence
      description: This switch is the car's connection to the MQTT broker
      selector:
        entity:
          domain: switch
mode: single
trigger:
- platform: state
  entity_id: !input 'car_presence'
  to: 'on'
- platform: state
  entity_id: !input 'car_presence'
  to: unavailable
  for:
    minutes: 1
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input 'car_presence'
      state: 'on'
    - condition: state
      entity_id: !input 'garage_door'
      state: closed
    sequence:
    - service: cover.open_cover
      entity_id: !input 'garage_door'
  - conditions:
    - condition: state
      entity_id: !input 'car_presence'
      state: unavailable
    - condition: state
      entity_id: !input 'garage_door'
      state: open
    sequence:
    - service: cover.close_cover
      entity_id: !input 'garage_door'
  default: []
