blueprint:
  name: Octoprint_Discovery_Helper - 2023-03-14
  author: SirGoodenough
  description: 'This is Blueprint is provided as a helper for people using the
    Octoprint Plugin called [OctoPrint-HomeAssistant](https://github.com/cmroche/OctoPrint-HomeAssistant).
    Within that Plugin there are several suggested Home Assistant Scripts &
    automations, and this will build them all for you.


    📩 There is not an official version control system for Blueprints. However I have
    found something that comes pretty close. It is not perfect, but for **MOST**
    Blueprints, it does just fine. I encourage you to check this script out and use
    it to easily check if I have updated this blueprint. 🔗 [koter84 Blueprint Update Script](https://github.com/koter84/HomeAssistant_Blueprints_Update/)


    [Community link for this blueprint](https://here)
    '
  source_url: 'https://raw.githubusercontent.com/SirGoodenough/HA_Blueprints/Octoprint/Automations/Octoprint_Discovery_Helper.yaml'
  homeassistant:
    min_version: 2023.3.0
  domain: automation
  input:
    base_topic:
      name: MQTT Topic for the printer
      description: 'This needs to be the base topic that you added into the Octoprint
        MQTT Plug-in. Use the instruction file for details where to find it.
        '
      selector:
        text:
          multiline: false
    device_id:
      name: Valuee of the Home Assistant Discovery node id
      description: 'This needs to be the 
        ```Discovery settings - Node ID``` 
        that you added into the Octoprint Homeassistant Discovery Plug-in. 
        USe the instruction file for details where to find it.
        '
      selector:
        text:
          multiline: false
    device_name:
      name: Name of the Home Assistant Discovery Device
      description: 'This needs to be the 
        ```Device settings - Device name``` 
        that you added into the Octoprint Homeassistant Discovery Plug-in. 
        USe the instruction file for details where to find it.
        '
      selector:
        text:
          multiline: false
    print_status:
      name: print status sensor
      description: 'Sensor that looks like this:
        ```sensor.[Home Assistant Discovery Device]_print_status```
        Was generated by octoprint homeassistant discovery.
        '
      default: sensor.[octoprint device name]_print_status
      selector:
        entity:
          multiple: false
          domain: sensor
    print_state:
      name: print status sensor
      description: 'Sensor that looks like this:
        ```binary_sensor.[Home Assistant Discovery Device]_printing```
        Was generated by octoprint homeassistant discovery.
        '
      default: binary_sensor.[octoprint device name]_printing
      selector:
        entity:
          multiple: false
          domain: binary_sensor
    printhead_temp:
      name: printhead temperature sensor
      description: 'Sensor that looks like this:
        ```sensor.[Home Assistant Discovery Device]_tool_0_temperature```
        Was generated by octoprint homeassistant discovery.
        '
      default: sensor.[octoprint device name]_tool_0_temperature
      selector:
        entity:
          multiple: true
          domain: sensor
    octoprint_shutdown:
      name: octoprint shutdown button
      description: 'Button that looks like this:
        ```button.[Home Assistant Discovery Device]__shutdown_system```
        Was generated by octoprint homeassistant discovery.
        '
      default: button.[octoprint device name]_shutdown_system
      selector:
        entity:
          multiple: false
          domain: button
    safe_shutdown:
      name: safe shutdown button
      description: 'Button that looks like this:
        ```button.[Home Assistant Discovery Device]_safe_shutdown_button```
        For the first run of this blueprint install any button so the BP
        will run. This is a chicken-egg problem where the button will not
        actually exist UNTIL AFTER the BP is first run. 
        You will have to come back and change this entry to the actual button
        created for safe shutdown.
        It will exist after the BP sucessfully runs triggered by starting
        Octoprint from off.
        '
      default: button.[octoprint device name]_safe_shutdown_button
      selector:
        entity:
          multiple: false
          domain: button
    home_button: 
      name: Custom command for Home Button
      description: 'Use this to send a custom GCode command to the printer.'
      default: '["x", "y", "z"]'
      selector:
        text:
          multiline: false
    bed_level_button:
      name: Custom GCode command for the Bed Level Button
      description: 'Use this to send a custom GCode command to the printer.'
      default: 'G29'
      selector:
        text:
          multiline: false
    present_button:
      name: Custom jog command for the Presentation Button
      description: 'Use this to send a custom GCode command to the printer.'
      default: '{"x": 0, "y": 180, "z": 80, "absolute": 1}'
      selector:
        text:
          multiline: false
    aux_1:
      name: Custom GCode command for Aux Button 1
      description: 'Use this to send a custom GCode command to the printer.'
      default: 'M117 Test Aux1 button'
      selector:
        text:
          multiline: false
    aux_2:
      name: Custom GCode command for Aux Button 2
      description: 'Use this to send a custom GCode command to the printer.'
      default: 'M117 Test Aux2 button'
      selector:
        text:
          multiline: false

variables:
  h_b_cmnd: !input home_button
  bl_b_cmnd: !input bed_level_button
  p_b_cmnd: !input present_button
  a1_b_cmnd: !input aux_1
  a2_b_cmnd: !input aux_2
  printer_topic: !input base_topic
  dv_name: !input device_name
  dv_id: !input device_id
  ha_topic: 'homeassistant/button/{{ dv_id }}'
    # Device Parameters for MQTT Discovery
  avty_t: '~mqtt'
  pl_avail: 'connected'
  pl_not_avail: 'disconnected'
  ids: 'octoprint-BP_{{ dv_id }}'
  dname: '{{ dv_name }} Blueprint Helper'
  mf: 'SirGoodenough'
  mdl: 'Octoprint_Discovery_Helper'
  sa: 'home'
  sw: '2023-03-14'
  hw: 'https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Octoprint_Discovery_Helper.yaml'
  cu: 'https://TBD'
    # Button Parameters for MQTT Discovery
      # Home Button
  h_local: home_button
  h_c_topic: '{{ ha_topic }}_{{ h_local }}/config'
  h_bname: '{{ dv_name }} {{ h_local }}'
  h_uniq_id: '{{ dv_id }}_{{ h_local }}'
  h_ic: mdi:home
  h_cmd_t: '~hassControl/home'
  h_pl_prs: '{{ h_b_cmnd }}'
      # Bed Level Button
  bl_local: bed_level_button
  bl_c_topic: '{{ ha_topic }}_{{ bl_local }}/config'
  bl_bname: '{{ dv_name }} {{ bl_local }}'
  bl_uniq_id: '{{ dv_id }}_{{ bl_local }}'
  bl_ic: mdi-spirit-level
  bl_cmd_t: '~hassControl/commands'
  bl_pl_prs: '{{ bl_b_cmnd }}'
      # Presentation Button
  p_local: presentation_button
  p_c_topic: '{{ ha_topic }}_{{ p_local }}/config'
  p_bname: '{{ dv_name }} {{ p_local }}'
  p_uniq_id: '{{ dv_id }}_{{ p_local }}'
  p_ic: mdi-gift
  p_cmd_t: '~hassControl/jog'
  p_pl_prs: '{{ p_b_cmnd }}'
      # User Aux 1 Button
  a1_local: aux_1_button
  a1_c_topic: '{{ ha_topic }}_{{ a1_local }}/config'
  a1_bname: '{{ dv_name }} {{ a1_local }}'
  a1_uniq_id: '{{ dv_id }}_{{ a1_local }}'
  a1_ic: mdi-hand-extended-outline
  a1_cmd_t: '~hassControl/commands'
  a1_pl_prs: '{{ a1_b_cmnd }}'
      # User _aux 2 Button
  a2_local: aux_2_button
  a2_c_topic: '{{ ha_topic }}_{{ a2_local }}/config'
  a2_bname: '{{ dv_name }} {{ a2_local }}'
  a2_uniq_id: '{{ dv_id }}_{{ a2_local }}'
  a2_ic: mdi-hand-extended
  a2_cmd_t: '~hassControl/commands'
  a2_pl_prs: '{{ a2_b_cmnd }}'
      # Safe Shutdown Button
  sd_local: safe_shutdown_button
  sd_c_topic: '{{ ha_topic }}_{{ sd_local }}/config'
  sd_bname: '{{ dv_name }} {{ sd_local }}'
  sd_uniq_id: '{{ dv_id }}_{{ sd_local }}'
  sd_ic: mdi-power
  sd_cmd_t: '~/blueprint/shutdown'
  sd_pl_prs: 'press'
    # Action variables
  printing_state: !input print_state
  printer_status: !input print_status

trigger:
- platform: state
  entity_id: !input print_status
  id: "start_up"
  to: "Operational"
- platform: numeric_state
  entity_id: !input printhead_temp
  id: "in_range"
  below: "40.0"
  above: "35.0"
  for: 00:01:00
- platform: state
  entity_id: !input safe_shutdown
  id: "shutdown_pressed"

action:
- alias: Determine if there was an actionable event
  choose:
  - conditions:
    - alias: Printer NOT running
      and:
        - condition: template
          value_template: '{{ states( printing_state ) != "on" }}'
        - alias: NOT the start-up trigger
          or:
          - condition: trigger
            id: in_range
          - condition: trigger
            id: shutdown_pressed
    sequence:
      - alias: Shut down Octoprint
        service: button.press
        entity_id: !input octoprint_shutdown
      - alias: Hold for the MQTT connection do go away
        wait_template: "{{ is_state( printer_status, 'unavailable' ) }}"
        timeout: "00:05:00"
      - alias: Hold a bit longer to make sure the PI has stopped
        delay: 00:00:59
      - alias: Kill the wall plug
        service: homeassistant.turn_off
        entity_id: switch.sonoff_s40lite_switch_2

  default:
  - alias: Home Button Create
    service: mqtt.publish
    data:
      "topic": "{{ h_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ h_bname }}",
          "uniq_id": "{{ h_uniq_id }}",
          "ic": "{{ h_ic }}",
          "cmd_t": "{{ h_cmd_t }}",
          "pl_prs": "{{ h_pl_prs }}"
        }
  - delay: 00:00:15
  - alias: Bed Level Button Create
    service: mqtt.publish
    data:
      "topic": "{{ bl_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ bl_bname }}",
          "uniq_id": "{{ bl_uniq_id }}",
          "ic": "{{ bl_ic }}",
          "cmd_t": "{{ bl_cmd_t }}",
          "pl_prs": "{{ bl_pl_prs }}"
        }
  - delay: 00:00:15
  - alias: Presentation Button Create
    service: mqtt.publish
    data:
      "topic": "{{ p_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ p_bname }}",
          "uniq_id": "{{ p_uniq_id }}",
          "ic": "{{ p_ic }}",
          "cmd_t": "{{ p_cmd_t }}",
          "pl_prs": "{{ p_pl_prs }}"
        }
  - delay: 00:00:15
  - alias: User Aux 1 Button Create
    service: mqtt.publish
    data:
      "topic": "{{ a1_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ a1_bname }}",
          "uniq_id": "{{ a1_uniq_id }}",
          "ic": "{{ a1_ic }}",
          "cmd_t": "{{ a1_cmd_t }}",
          "pl_prs": "{{ a1_pl_prs }}"
        }
  - delay: 00:00:15
  - alias: User Aux 2 Button Create
    service: mqtt.publish
    data:
      "topic": "{{ a2_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ a2_bname }}",
          "uniq_id": "{{ a2_uniq_id }}",
          "ic": "{{ a2_ic }}",
          "cmd_t": "{{ a2_cmd_t }}",
          "pl_prs": "{{ a2_pl_prs }}"
        }
  - delay: 00:00:15
  - alias: Safe Shutdown Button Create
    service: mqtt.publish
    data:
      "topic": "{{ sd_c_topic }}"
      "retain": true
      "payload": >
        { "~": "{{ printer_topic }}",
          "avty_t": "{{ avty_t }}",
          "pl_avail": "{{ pl_avail }}",
          "pl_not_avail": "{{ pl_not_avail }}",
          "dev": {
            "ids": "{{ ids }}",
            "name": "{{ dname }}",
            "mf": "{{ mf }}",
            "mdl": "{{ mdl }}",
            "sa": "{{ sa }}",
            "sw": "{{ sw }}",
            "hw": "{{ hw }}",
            "cu": "{{ cu }}"
          },
          "name": "{{ sd_bname }}",
          "uniq_id": "{{ sd_uniq_id }}",
          "ic": "{{ sd_ic }}",
          "cmd_t": "{{ sd_cmd_t }}",
          "pl_prs": "{{ sd_pl_prs }}"
        }
mode: parallel
max: 5
max_exceeded: silent
