blueprint:
  name: Person Alert Honitor - 2023-02-26
  description: 'This is Blueprint that This BluePrint will monitor a person or
    persons, and when they ''enter'' or ''leave'' the zone or zones you pick,
    it will trigger an action for both enter and leave phases.
    Yes, it will watch multiple people and multiple zones at the same time!

    I use this BluePrint to follow family members around during their day so that
    the family members at home know where their loved ones are.

    The monitored areas need to be set up as zones in Home Assistant. SEE:
      [HA ZONES LINK](https://www.home-assistant.io/integrations/zone/)
      [![Open your Home Assistant instance and show your zones.](https://my.home-assistant.io/badges/zones.svg)](https://my.home-assistant.io/redirect/zones/)


    The person needs LAT/LOG software running to report their location.
    I use Life360, but the Home Assistant App running on their phone will also
    work. There are likely other location monitoring methods but I am not aquainted
    with any of them. SEE:

      [![Open your Home Assistant instance and show your people.](https://my.home-assistant.io/badges/people.svg)](https://my.home-assistant.io/redirect/people/)

      [LIFE360 INTEGRATION LINK ](https://www.home-assistant.io/integrations/life360/)

      [PERSON INTEGRATION LINK ](https://www.home-assistant.io/integrations/person/)


    📩 There is not an official version control system for Blueprints. However I have
    found something that comes pretty close. It is not perfect, but for **MOST**
    Blueprints, it does just fine. I encourage you to check this script out and use
    it to easily check if I have updated this blueprint.  🔗 [koter84 Blueprint Update Script](https://github.com/koter84/HomeAssistant_Blueprints_Update/)


    [Community link for this blueprint](TBD)
    '
  source_url: https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Person_Alert_Blueprint.yaml
  homeassistant:
    min_version: 2023.2.0
  domain: automation
  input:
    people2monitor:
      name: Person or People to follow
      description: 'Select the Person you want this BP to trigger on for this action.
        Multiples are allowed.
        '
      selector:
        entity:
          multiple: true
          domain: person
    zone2monitor:
      name: Zone to watch
      description: 'Select the Zone you want this BP to trigger on when this person
        enters or leaves it.
        Multiples are allowed.
        '
      selector:
        entity:
          multiple: true
          domain: zone
    enter_action:
      name: Enter the Zone Action
      description: 'Build the action here that you want to happen when they enter
        this zone. There is a ''Persistent Notification'' example in [The Docs File.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Person_Alert_Blueprint.md)

        If you want to do a TTS I suggest [This Blueprint.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/tts_All_Message_Script_Blueprint.yaml)

        If you want to play a sound effect or music I suggest [This Blueprint.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/play_media_file_script.yaml)

        There is also a built-in [Actionable Notification Script Blueprint](https://github.com/home-assistant/core/blob/master/homeassistant/components/script/blueprints/confirmable_notification.yaml)
        that could work here.  It is included with Home Assistant.
        '
      default: []
      selector:
        action: {}
    leave_action:
      name: Leave the Zone Action
      description: 'Build the action here that you want to happen when they leave
        this zone. There is a ''Persistent Notification'' example in [The Docs File.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Automations/Person_Alert_Blueprint.md)

        If you want to do a TTS I suggest [This Blueprint.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/tts_All_Message_Script_Blueprint.yaml)

        If you want to play a sound effect or music I suggest [This Blueprint.](https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/play_media_file_script.yaml)
        '
      default: []
      selector:
        action: {}
    enable_time:
      name: Time of day to begin action(s)
      description: 'Set this for the time of day you want to allow action(s) to begin.
        Leave as is to always be enabled.'
      default: 00:00:00
      selector:
        time: {}
    disable_time:
      name: Time of day to end action(s)
      description: 'Set this for the time of day you want action(s) to end.
        Leave as is to always be enabled.'
      default: 00:00:00
      selector:
        time: {}
    weekday:
      name: Day of the week to allow action(s)
      description: 'Change options if you want to include or exclude any specific day.
        All days are selected by default.'
      default:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          custom_value: false
          multiple: true

trigger: 
  - platform: state
    id: Persons state has changed
    entity_id: !input people2monitor

condition:
  - alias: Make sure there even was a move
    condition: template
    value_template: '{{ to_state != from_state }}'
  - alias: Make sure it's not an I'm Lost move
    condition: template
    value_template: '
      {{ not to_state in (''unknown'',''unavailable'',''none'',''None'','''') and
      not from_state in (''unknown'',''unavailable'',''none'',''None'','''') }}
      '
  - alias: Only allow execution within selected Hours / Weekdays
    condition: time
    after: !input 'enable_time'
    before: !input 'disable_time'
    weekday: !input 'weekday'

variables:
  people2monitor_var: !input people2monitor
  zone2monitor_var: !input zone2monitor
  friend_zone: >
    {% set ns = namespace(zone=[]) %}
    {% for z in zone2monitor_var %}
    {% set ns.zone = ns.zone + [states[z].attributes.friendly_name] %}
    {% endfor %} 
    {{ ns.zone }}
  to_state: '{{ trigger.to_state.state }}'
  from_state: '{{ trigger.from_state.state }}'

action:
# - alias: 'Fire variable reporting event. This is for optional troubleshooting data.'
#   event: person_alert_variables
#   event_data:
#     people2monitor: '{{ people2monitor_var }}'
#     zone2monitor: '{{ zone2monitor_var }}'
#     friend_zone: '{{ friend_zone }}'
#     to_state: '{{ to_state }}'
#     from_state: '{{ from_state }}'

- alias: Determine if there was an actionable event
  choose:
  - conditions:
    - alias: Has Person arrived at Zone?
      condition: and
      conditions:
      - condition: template
        alias: person is in target zone
        value_template:
          '{{ to_state in friend_zone }}'
      - condition: template
        alias: person is arriving from another zone
        value_template:
          '{{ not from_state in friend_zone }}'
    sequence: !input enter_action
  - conditions:
    - alias: Person left Zone?
      condition: and
      conditions:
      - alias: Person was in Zone
        condition: template
        value_template:
          '{{ from_state in friend_zone }}'
      - alias: Person not in zone now
        condition: template
        value_template:
          '{{ not to_state in friend_zone }}'
    sequence: !input leave_action

mode: queued
max: 10
