blueprint:
  name: long_short_toggle_4_magic_cube_and_other_things - 2023-04-23
  author: SirGoodenough
  domain: script
  homeassistant:
    min_version: 2023.3.0
  source_url: https://github.com/SirGoodenough/HA_Blueprints/blob/master/Scripts/long_short_toggle_4_magic_cube.yaml
  description: >
    This script was invented to be used with my Magic Cube Blueprints. I released
    it as a standalone Script Blueprint because I saw others struggling with how
    so convert cube rotation to actions in other places.


    To use this blueprint, install it from the source in the normal way.
    After that add your unique name for the Script, and add an icon and change
    the entity_id if desired.
    You should only need to run the blueprint once, as you will be calling the
    unique name/entity you added above to use the code.
    This script has no inputs in the Blueprint screen because all the data is
    added to control the action live at each use.


    This requires you call this script with a couple of data values. One is a 
    positive or negative number between 360 and -360 that in the original,
    represents the input angle from the cube movement.
    The other data point is the entity of the device(s) that you are trying 
    o control. Only 1 of the short_entity or long_entity is required 4 this
    Blueprint to work.
    
    ***NOTE:*** the trigger variable belos will be different for Z2M and ZHA
    and others. Look at my documentation for that cube integration help if
    you need it.

    Sample call / use of this script:
      ```yaml
      - service: script.cube_long_short_toggle
        data:
          angle: '{{ trigger.payload_json.action_angle | float(0.0) }}'
          short_entity: light.kitchen_down_lights
          long_entity: light.kitchensink
      ```

fields:
  angle:
    name: Angle to represent switch function
    description: >-
      This is the angle to be used in the calculation for switch function
    required: true
    example: "20.7"
    selector:
      number:
        min: -360
        max: 360
        step: 0.1
        mode: box
  short_entity:
    name: Entity to control with short rotation
    description: >-
      Add the entity you want to control here with a short rotation of cube.
      One of the long or the short entities are required but not both.
    required: false
    example: light.kitchen_down_lights
    selector:
      entity:
        multiple: true
  long_entity:
    name: Entity to control with long rotation
    description: >-
      Add the entity you want to control here with a long rotation of the cube.
      One of the long or the short entities are required but not both.
    required: false
    example: switch.dust_collector
    selector:
      entity:
        multiple: true
sequence:
  - choose:
    - conditions:
      - alias: "Pseudo short press with (angle | abs) <= 100"
        condition: template
        value_template: "{{ angle | abs <= 100 }}"
      sequence:
        - alias: Check if a short entity was provided
          if: '{{ not short_entity in (''none'', ''null'', ''unavailable'', '''') }}'
          then: 
            - alias: "Send short_press"
              service: homeassistant.toggle
              target:
                entity_id: '{{ short_entity }}'
    default:
      - alias: Check if a long entity was provided
        if: '{{ not long_entity in (''none'', ''null'', ''unavailable'', '''') }}'
        then: 
          - alias: "Send long_press"
            service: homeassistant.toggle
            target:
              entity_id: '{{ long_entity }}'
icon: mdi-toggle-switch-outline
mode: queued
max: 10
