blueprint:
  name: TTS Google Translate Say Message_2021-12-15
  description: A script that uses tts google_translate_say to send a message to a
    google speaker
  source_url: https://gist.github.com/SirGoodenough/ecf747f3bc399f088a13853cf80ec12b
  domain: script
  homeassistant:
    min_version: 2021.11.0
  input:
    speaker_target:
      name: Device(s) to speak thru
      description: This uses google_translate to send a text message
      selector:
        entity:
          domain: media_player
    speaker_language:
      name: Speaker Language
      description: 'Check the complete list of [supported languages] for allowed values.
        [ https://cloud.google.com/text-to-speech/docs/voices The 2 letter acronym
        (example- en for english) is all that is used here. ]

        This defaults to en (english) so you do not have to send the data from the
        calling script if you are using that.'
      default: en
    announcement_message:
      name: Spoken message
      description: 'Type your message here:'
      default: It matters not what I say.
      selector:
        text:
          multiline: true
mode: queued
sequence:
- service: tts.google_translate_say
  data:
    entity_id: !input 'speaker_target'
    message: !input 'announcement_message'
    language: !input 'speaker_language'
