blueprint:
  name: TTS Cloud Message_2021-08-26
  description: A script that uses tts-cloud via Nabu-Casa to send a message to a google
    speaker
  source_url: https://gist.github.com/SirGoodenough/7eea35ad75daf883a7938c0bc99499bd
  domain: script
  input:
    speaker_target:
      name: Device(s) to speak thru
      description: This uses tts-cloud and will only work when using Nabu-Casa
      selector:
        entity:
          domain: media_player
    speaker_gender:
      name: Speaker Gender
      description: Select speaker gender male or female
      default: male
      selector:
        select:
          options:
          - female
          - male
    speaker_language:
      name: Speaker Language
      description: 'Select Language code.  See-> (https://www.nabucasa.com/config/tts/)
        This defaults to en (english) so you do not have to send the data from the
        calling script if you don''t need to change it. '
      default: en-AU
    announcement_message:
      name: Spoken message
      description: Type your message here
      default: It matters not what I say.
      selector:
        text:
          multiline: true
mode: queued
sequence:
- service: tts.cloud_say
  data:
    entity_id: !input 'speaker_target'
    message: !input 'announcement_message'
    options:
      gender: !input 'speaker_gender'
    language: !input 'speaker_language'
