blueprint:
  name: TTS Google Translate Say Message_2021-08-26
  description: A script that uses tts google_translate_say to send a message to a
    google speaker
  source_url: https://gist.github.com/SirGoodenough/ecf747f3bc399f088a13853cf80ec12b
  domain: script
  input:
    speaker_target:
      name: Device(s) to speak thru
      description: This uses google_translate to send a text message
      selector:
        entity:
          domain: media_player
    speaker_language:
      name: Speaker Language
      description: Check the complete list of [supported languages] (https://translate.google.com/intl/en_ALL/about/languages/)
        (languages where -Talk- feature is enabled in Google Translate) for allowed
        values. This defaults to en (english) so you do not have to send the data
        from the calling script if you don't need to change it.
      default: en
    announcement_message:
      name: Spoken message
      description: 'Type your message here:'
      default: It matters not what I say.
      selector:
        text:
          multiline: true
mode: queued
sequence:
- service: tts.google_translate_say
  data:
    entity_id: !input 'speaker_target'
    message: !input 'announcement_message'
    language: !input 'speaker_language'
