blueprint:
  name: Testing Plueprints
  description: Start a timer when input boolean is triggered
  domain: automation
#  source_url: ""
  input:
    start_it:
      name: Trigger On
      selector:
        entity:
          domain: input_boolean
    timer_target:
      name: Timer
      selector:
        target:
          entity:
          domain: timer
    media_player_target:
      name: Which Speaker
      selector:
        target:
          entity:
          domain: media_player
    message:
      name: Message (Optional)
      description: Announcement that the timer is starting
      default: 
    tts_gender:
      name: TTS Gender (Optional)
      description: 'Default: "female"'
      default: female
    tts_language:
      name: TTS Language (Optional)
      description: 'Default: "en-US"'
      default: en-US


# If the timer is called to action:
#  -announce the start
#  -wait
#  -signal the end

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input start_it
  from: "off"
  to: "on"

action:
  - service: timer.start
    target: !input timer_target
  - service: tts.cloud_say
    target: !input media_player_target
    data:
      message: !input message
      options:
        gender: !input tts_gender
      language: !input tts_language
  - wait_for_trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.flushtime5
  - service: media_player.play_media
    target: !input media_player_target
    data:
      media_content_id: !secret Gong
      media_content_type: audio/mp3
  - service: input_boolean.turn_off
    entity_id: !input start_it
