blueprint:
  name: Timer Start
  description: Start a timer when input boolean is triggered
  domain: automation
#  source_url: ""
  input:
    start_it:
      name: Trigger On
      selector:
        entity:
          domain: input_boolean
    timer_target:
      name: Timer
      selector:
        target:
          entity:
            domain: timer
    media_player_target:
      name: Which Speaker
      selector:
        target:
          entity:
            domain: media_player


# If the timer is called to action:
#  -announce the start
#  -wait
#  -signal the end

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input start_it
  from: "off"
  to: "on"

action:
  - service: input_boolean.turn_off
    target: !input start_it
  - service: timer.start
    target: !input timer_target
  - service: tts.cloud_say
    data:
      entity_id: !input media_player_target
      message: "My Legs"
      options:
        gender: female
      language: de-DE
  - wait_for_trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: !input timer_target
  - service: media_player.play_media
    data:
      entity_id: !input media_player_target
      media_content_id: !secret Gong
      media_content_type: audio/mp3
