esphome:
  name: bt1

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bt1encrypt

ota:
  password: !secret bt1otapw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Bt1 Fallback Hotspot"
    password: !secret ap_password

bluetooth_proxy:
  active: true
    
sensor:
  - platform: dht
    pin: GPIO21
    model: AM2302
    temperature:
      name: "Kitchen2 Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Kitchen2 Humidity"
      accuracy_decimals: 1
    update_interval: 60s
