substitutions:
    name: "bt1"
    board: "esp32dev"
    friendly_name: Kitchen2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bt1encrypt

ota:
  password: !secret bt1otapw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret ap_password

bluetooth_proxy:
  active: true

sensor:
  - platform: dht
    pin: GPIO21
    model: AM2302
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 60s

button:
  - platform: safe_mode
    name: "Safe Mode Boot ${name} ${friendly_name}"
    entity_category: diagnostic
  - platform: restart
    name: "Restart ${name} ${friendly_name}"
    entity_category: diagnostic
  - platform: shutdown
    name: "Shutdown ${name} ${friendly_name}"
    entity_category: diagnostic