substitutions:
  name: "bt1"
  board: "esp32dev"
  friendly_name: Kitchen2
  frame_type: esp-idf

packages:
  device_base: !include /config/esphome/packages/sg_base.yaml

esphome:
  name_add_mac_suffix: false

bluetooth_proxy:
  active: true

sensor:
  - platform: dht
    pin: GPIO21
    model: AM2302
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 60s
