substitutions:
  name: "bt2"
  friendly_name: Garage
  frame_type: esp-idf

packages:
  device_base: !include /config/esphome/packages/sg_base.yaml

wifi:
  manual_ip:
    gateway: !secret chaloupkaabode_gateway
    subnet: !secret chaloupkaabode_subnet
    static_ip: !secret bt2_IP

esphome:
  name_add_mac_suffix: false

bluetooth_proxy:
  active: true

sensor:
  - platform: dht
    pin: GPIO21
    model: AM2302
    temperature:
      name: "${friendly_name} Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      accuracy_decimals: 1
    update_interval: 60s
