substitutions:
  board: esp01_1m
  name: cabnetio
  friendly_name: Cabnetio

packages:
  device_base: !include /config/esphome/packages/sg_8266_base.yaml

esphome:
  area: kitchen
  name_add_mac_suffix: false

wifi:
  manual_ip:
    gateway: !secret chaloupkaabode_gateway
    subnet: !secret chaloupkaabode_subnet
    static_ip: !secret cabnetio_IP
    dns1: !secret chaloupkaabode_gateway

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    name: "${friendly_name} Button"
    RESTORE_DEFAULT_OFF
    on_press:
      then:
        - light.toggle: light_1

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "${friendly_name} Light"
    id: light_1
    output: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: yes