external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  legacy_triggers: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: z2m
  password: wi8DpNVTWu989Nk
  server: mqtt://core-mosquitto:1883
  client_id: Z2M_Mama
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0883963e9ec8eb119a9dc5c3de5b81b4-if00-port0
advanced:
  log_level: info
  pan_id: 6754
  channel: 25
  network_key:
    - 11
    - 3
    - 15
    - 7
    - 19
    - 1
    - 13
    - 5
    - 0
    - 2
    - 14
    - 6
    - 8
    - 0
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: ISO_8601
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true
